const app=document.querySelector('#app'),key=document.querySelector('#api-key'),toast=document.querySelector('#toast');
async function api(path,options={}){options.headers={...(options.headers||{}),'X-API-Key':key.value,'Content-Type':'application/json'};const r=await fetch('/api/v1'+path,options);if(r.status===204)return null;const j=await r.json();if(!r.ok)throw new Error(j.message||r.statusText);return j}
function msg(text){toast.textContent=text;toast.style.display='block';setTimeout(()=>toast.style.display='none',2500)}
function date(d){return d?new Date(d).toLocaleString():'-'}
async function dashboard(){const {data}=await api('/stats');app.innerHTML=`<h2>仪表盘</h2><div class="cards"><div class="card">证书总数<strong>${data.total}</strong></div><div class="card">有效<strong>${data.by_status.valid||0}</strong></div><div class="card">即将到期<strong>${data.by_status.expiring_soon||0}</strong></div><div class="card">已过期<strong>${data.by_status.expired||0}</strong></div></div><div class="panel"><h3>7 天内到期</h3>${table(data.expiring_next_7d,['name','domain','days_to_expire','status'])}</div>`}
function table(rows,fields){return `<table><thead><tr>${fields.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${(rows||[]).map(row=>`<tr>${fields.map(x=>`<td>${row[x]??''}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
async function certificates(){const r=await api('/certificates?size=100');app.innerHTML=`<h2>证书</h2><div class="panel"><h3>登记证书</h3><form id="cert-form"><input name="name" placeholder="名称" required><input name="domain" placeholder="域名" required><input name="issuer" value="Internal CA" required><input name="serial_number" value="A001" required><select name="algorithm"><option>ECDSA</option><option>RSA</option></select><input name="key_bits" type="number" value="256"><input name="valid_from" type="datetime-local" required><input name="valid_until" type="datetime-local" required><input name="owner" placeholder="负责人"><select name="environment"><option>prod</option><option>staging</option><option>dev</option></select><button>登记</button></form></div><div class="panel">${table(r.data,['id','name','domain','days_to_expire','status'])}</div>`;document.querySelector('#cert-form').onsubmit=submitCert}
async function submitCert(e){e.preventDefault();const f=new FormData(e.target),body=Object.fromEntries(f);body.key_bits=Number(body.key_bits);body.valid_from=new Date(body.valid_from).toISOString();body.valid_until=new Date(body.valid_until).toISOString();body.sans=[];body.tags=[];body.contacts=[];body.notify_threshold_days=30;body.renew_threshold_days=14;body.deploy_target_ids=[1];await api('/certificates',{method:'POST',body:JSON.stringify(body)});msg('登记成功');certificates()}
async function renewals(){const r=await api('/renewals?size=100');app.innerHTML='<h2>续期记录</h2><div class="panel">'+table(r.data,['id','certificate_id','triggered_by','status','attempt','new_serial'])+'</div>'}
async function targets(){const {data}=await api('/targets');app.innerHTML='<h2>部署目标</h2><div class="panel">'+table(data,['id','name','host','port','method','enabled'])+'</div>'}
async function tasks(){const {data}=await api('/tasks');app.innerHTML=`<h2>后台任务</h2><div class="panel"><table><tr><th>名称</th><th>间隔</th><th>结果</th><th>运行次数</th><th></th></tr>${data.map(x=>`<tr><td>${x.name}</td><td>${x.interval}</td><td>${x.last_result||'-'}</td><td>${x.runs}</td><td><button onclick="runTask('${x.name}')">立即运行</button></td></tr>`).join('')}</table></div>`}
async function runTask(name){const {data}=await api('/tasks/run',{method:'POST',body:JSON.stringify({name})});msg(data.detail);tasks()}
const views={dashboard,certificates,renewals,targets,tasks};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>views[b.dataset.view]().catch(e=>msg(e.message)));dashboard().catch(e=>msg(e.message));
